services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: redacode
      POSTGRES_PASSWORD: password
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge