server:
  port: 4040

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: redacode
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true